### ISSUE TITLE
Using python2.7 i get this error

### ISSUE THREAD

**Issue by winner8** [rbavishi/Habitican-Curse#11]
Traceback (most recent call last):
  File "/usr/local/bin/habitican-curse", line 45, in <module>
    curses.wrapper(main)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/bin/habitican-curse", line 32, in main
    G.intf.Init()
  File "/usr/local/lib/python2.7/dist-packages/habitican_curse/interface.py", line 36, in Init
    G.HabitMenu.SetXY(1, 2)
AttributeError: 'NoneType' object has no attribute 'SetXY'

anyone have any suggestions?

**Comment by jasonuher** [comment]
I have this issue sometimes when the terminal size isn't large enough.  Try using a full screen terminal and see if that fixes.  Some better bounds checking for the curses interface may be in order.

**Comment by winner8** [comment]
Which one do you remember? I am currently using sakura.

**Comment by jasonuher** [comment]
1) mostly I mean try using a "larger terminal window", the actual terminal program shouldn't matter.

This might also be related to the API V3 switch.  You could test this by pulling the V3 update (https://github.com/jasonuher/Habitican-Curse) and trying it out.  It could use some more testing before it's integrated officially anyway

**Comment by jasonuher** [comment]
@winner8 does this function properly with the latest master branch?

**Comment by rbavishi** [comment]
Closed until someone reports a similar problem. Should be fixed though.
