### ISSUE TITLE
Allow for custom ordering and show/hide in the item lists

### ISSUE THREAD

**Issue by jasonuher** [rbavishi/Habitican-Curse#22]
Generated by the #18 mega thread from @LordVladneutral.

Users should be able to:
1. sort their dailies and habits properly
2. control which ones are shown similar to the website ("all", "due", etc)

**Comment by LordVladneutral** [comment]
I would add that sorting by name would be nice too:
I recently started to add an icon at the start of my tasks so it would help sorting them by category.
