### ISSUE TITLE
Enhance habitica.py to ask for user credentials if .habiticarc doesn't have them

### ISSUE THREAD

**Issue by kbavishi** [rbavishi/Habitican-Curse#3]
We can't assume that the user has entered his credentials in the correct manner in `.habiticarc`. Eg. What if he enters the key followed by the UUID?

We should maybe let .habiticarc be a collection of key-value pairs to avoid confusion. Eg.

```
uuid=wayne_rooney
key=ballondor
```

Also, asking the user to create this file is a little cumbersome, and `habitica.py` should not assume that it has been created. 

Let `habitica.py` first check if `.habiticarc` exists and if it contains the user credentials. If not, it should create the file itself before communicating with the server

**Comment by rbavishi** [comment]
Have added the functionality. Check if it is working and close the issue.

**Comment by rbavishi** [comment]
Functionality added and is working perfectly.
