### ISSUE TITLE
Make available via pip

### ISSUE THREAD

**Issue by NickTomlin** [rbavishi/Habitican-Curse#4]
It would be fantastic if this were an executable available via pip instead of manual installation.

**Comment by rbavishi** [comment]
Hi Nick, thanks for bringing it to my attention. The manual installation is clumsy at best. I've added a pip installation. You can do it using `sudo pip install habitican_curse`. Refer to the README for more details.

**Comment by NickTomlin** [comment]
Awesome. Thanks!
