### ISSUE TITLE
[minor] Mac terminal backspace doesn't work as expected

### ISSUE THREAD

**Issue by JamesOwers** [rbavishi/Habitican-Curse#6]
Unsure if this is expected behaviour: when you hit `:` to type a command, hitting backspace produces a carat e.g.
<img width="150" alt="screen shot 2015-11-20 at 19 16 14" src="https://cloud.githubusercontent.com/assets/3524723/11309344/3b8db5ae-8fbb-11e5-835f-bab80e88d88b.png">

**Comment by rbavishi** [comment]
Well, this is known problem in Mac - curses doesn't identify the backspace properly (See https://bugs.python.org/issue23598). However, do try the attached patch out. Let me know if it makes a difference. If anything changes, could you send me a snapshot like before please? Thanks a lot!

```
patch screen.py < mac_patch.txt
```

[mac_patch.txt](https://github.com/rbavishi/Habitican-Curse/files/40558/mac_patch.txt)

**Comment by JamesOwers** [comment]
Patch worked a charm. Fills overspill with `?` characters but these are ignored e.g.
<img width="193" alt="screen shot 2015-11-20 at 21 25 58" src="https://cloud.githubusercontent.com/assets/3524723/11312373/79772dd4-8fcd-11e5-9095-e6e72a86c1c5.png">
<img width="196" alt="screen shot 2015-11-20 at 21 26 09" src="https://cloud.githubusercontent.com/assets/3524723/11312374/7977cdde-8fcd-11e5-8127-493b39dbc4d5.png">

**Comment by rbavishi** [comment]
Okay... at the cost of slight difference in efficiency (I don't think it will be noticeable), I've attached a patch which should take care of this problem too. Please let me know how it fares
[mac_patch_second.txt](https://github.com/rbavishi/Habitican-Curse/files/40750/mac_patch_second.txt)

**Comment by JamesOwers** [comment]
Great job, works perfectly.
