### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by binamkayastha** [rbavishi/Habitican-Curse#8]
Am I running it with the wrong python version? (trying to run it in python3)

**Comment by rbavishi** [comment]
Hi! Well, I did write the code with an editor setting to convert tabs into spaces. I'll check it again though. Also, I wrote it keeping python 2.7 in mind. I'd request you to try using the same, and see if the error persists. Thanks!

**Comment by jasonuher** [comment]
Inconsistent use of tabs and spaces should be fixed in pull request #12 (python 3 support is a whole different different can of worms)

**Comment by LordVladneutral** [comment]
habitican-curse                                
  File "/usr/bin/habitican-curse", line 17
    G.content = CT.ContentManager()
TabError: inconsistent use of tabs and spaces in indentation

Same here, it seems, I'll just wait until it's fixed then.

**Comment by rbavishi** [comment]
@LordVladneutral, sorry for the trouble. But I just want to confirm whether you're on the latest commit. I just did a grep and did not find any tabs. Could you check please?

**Comment by LordVladneutral** [comment]
Idk, I just installed it with sudo pip --install habitican-curses, shouldn't that do it ?
If not how do I check ?

**Comment by rbavishi** [comment]
Ah I see. We haven't incorporated all the recent changes into a new version on pip. I wrongly assumed you were following the github working branch as well. I'll fix it in a bit.

@jasonuher Do you have any immediate future plans or features? Otherwise I'll roll out a new version (although there a few things that require attention but are minor)

**Comment by rbavishi** [comment]
@LordVladneutral, try installing from pip again, I've uploaded the new version. Let me know if you face any more problems.

**Comment by LordVladneutral** [comment]
The error changed at least :

habitican-curse                  
Traceback (most recent call last):
  File "/usr/bin/habitican-curse", line 7, in <module>
    from habitican_curse import *
  File "/usr/lib/python3.5/site-packages/habitican_curse/__init__.py", line 10, in <module>
    import config as C
  File "/usr/lib/python3.5/site-packages/config.py", line 733
    except Exception, e:
SyntaxError: invalid syntax

it points on the ","

Am I using the wrong version of python ? I seem to use 3.5.2 and have 2.7 in my system.

**Comment by rbavishi** [comment]
Yes, only Python 2.7 is supported. 3.5 has different syntax.

**Comment by LordVladneutral** [comment]
I don't get how to open it with python 2.7

python2.7  usr/binhabitican-curse
doesn't seem to work.

I'm on Arch Linux.

**Comment by rbavishi** [comment]
That should have worked. What's the error?

**Comment by LordVladneutral** [comment]
python2.7 /usr/bin/habitican-curse                                                                                                                                                                                               :(
Traceback (most recent call last):
  File "/usr/bin/habitican-curse", line 7, in <module>
    from habitican_curse import *
ImportError: No module named habitican_curse

**Comment by rbavishi** [comment]
Right, so I think your pip was for python3, and installed the packages in the /usr/lib for python3. Could you try `sudo pip2.7 install habitican_curse`

**Comment by LordVladneutral** [comment]
python2.7 habitican-curse                                                                                                                                                                                                          :(
Traceback (most recent call last):
  File "habitican-curse", line 54, in <module>
    curses.wrapper(main)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "habitican-curse", line 39, in main
    G.reqManager.FetchData()
  File "/usr/lib/python2.7/site-packages/habitican_curse/request_manager.py", line 221, in FetchData
    logger.debug("Processing a TODO: %s" % str(i['text']))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 10: ordinal not in range(128)

Now it works, but there's this It connects and then I think rendering has a problem.

**Comment by rbavishi** [comment]
Which terminal are you using?

**Comment by LordVladneutral** [comment]
xfce4 standard terminal :
xfce4-terminal

**Comment by rbavishi** [comment]
https://bbs.archlinux.org/viewtopic.php?id=138470 might be of some help. Could you post the output of `locale -a | grep -i "utf8"`

**Comment by LordVladneutral** [comment]
en_GB.utf8
en_US.utf8
fr_BE.utf8
fr_FR.utf8

I'm reading the thread you gave.
Note, I'm not against using another terminal for this if you have any to recommend and that would faster solve the problem.

Edit : installed and tested with Konsole, getting exactly the same error. Also changing the locale or the encoding of the console doesn't seem to help.µ

Also I can paste non-ascii characters in there, and they display normally. (after extensive testings, it appears some rare ones may not display correctly.), as shows this line : (music special characters... rarely used)
 𝄁 𝄂 𝄃 𝄄 𝄅 𝄆 𝄇 𝄈 𝄉 𝄊 𝄋 𝄌 𝄍 𝄎 𝄏 𝄐 𝄑 𝄒 𝄓 𝄔 𝄕 𝄖 𝄗 𝄘 𝄙 𝄚 𝄛 𝄜 𝄝 𝄞 𝄟 𝄠 𝄡 𝄢 𝄣 𝄤 𝄥 𝄦 𝄩 𝄪 𝄫 𝄬 𝄭 𝄮 𝄯 𝄰 𝄱 𝄲 𝄳 𝄴 𝄵 𝄶 𝄷 𝄸 𝄹 𝄺 𝄻 𝄼 𝄽 𝄾 𝄿 𝅀 𝅁 𝅂 𝅃 𝅄 𝅅 𝅆 𝅇 𝅈 𝅉 𝅊 𝅋 𝅌 𝅍 𝅎 𝅏 𝅐 𝅑 𝅒 𝅓 𝅔 𝅕 𝅖 𝅗 𝅘 𝅙 𝅚 𝅛 𝅜 𝅝 𝅗𝅥 𝅘𝅥 𝅘𝅥𝅮 𝅘𝅥𝅯 𝅘𝅥𝅰 𝅘𝅥𝅱 𝅘𝅥𝅲 𝅥 𝅦 <0001d167> <0001d168> <0001d169> 𝅪 𝅫 𝅬 𝅭 𝅮 𝅯 𝅰 𝅱 𝅲 <0001d173> <0001d174> <0001d175> <0001d176> <0001d177> <0001d178> <0001d179> <0001d17a> <0001d17b> <0001d17c> <0001d17d> <0001d17e> <0001d17f> <0001d180> <0001d181> <0001d182> 𝆃 𝆄 <0001d185> <0001d186> <0001d187> <0001d188> <0001d189> <0001d18a> <0001d18b> 𝆌 𝆍 𝆎 𝆏 𝆐 𝆑 𝆒 𝆓 𝆔 𝆕 𝆖 𝆗 𝆘 𝆙 𝆚 𝆛 𝆜 𝆝 𝆞 𝆟 𝆠 𝆡 𝆢 𝆣 𝆤 𝆥 𝆦 𝆧 𝆨 𝆩 <0001d1aa> <0001d1ab> <0001d1ac> <0001d1ad> 𝆮 𝆯 𝆰 𝆱 𝆲 𝆳 𝆴 𝆵 𝆶 𝆷 𝆸 𝆹 𝆺 𝆹𝅥 𝆺𝅥 𝆹𝅥𝅮 𝆺𝅥𝅮 𝆹𝅥𝅯 𝆺𝅥𝅯 𝇁 𝇂 𝇃 𝇄 𝇅 𝇆 𝇇 𝇈 𝇉 𝇊 𝇋 𝇌 𝇍 𝇎 𝇏 𝇐 𝇑 𝇒 𝇓 𝇔 𝇕 𝇖 𝇗 𝇘 𝇙 𝇚 𝇛 𝇜 𝇝

Also seems like python 2.7's default encoding is ascii, I'm looking for a way to set that to UTF-8 to try.

**Comment by rbavishi** [comment]
@LordVladneutral - I'm very sorry, I think I've led you down a wrong path - I should have paid more attention to the error message. Do your task names contain special characters?

Edit : I found some bugs in the new logger functionality. Apologies for that. Your problem should be fixed (and I hope it's the last you have to face). I've updated the version on PyPi. Could you try the pip2.7 installation again? I apologise again for the numerous issues you're facing.

**Comment by LordVladneutral** [comment]
Ok, I'll try :) Don't worry, I'm here to test, and the primary objective of testing is improvement. The slightest improvement is a victory.

**Comment by LordVladneutral** [comment]
Here is what I have when I run it now. The error is evolving ;) it's a good sign. Again, it is connecting, then it stops.

```
python2.7 /usr/bin/habitican-curse                                                                                                                                                                                                 :(
Traceback (most recent call last):
  File "/usr/bin/habitican-curse", line 54, in <module>
    curses.wrapper(main)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/bin/habitican-curse", line 39, in main
    G.reqManager.FetchData()
  File "/usr/lib/python2.7/site-packages/habitican_curse/request_manager.py", line 226, in FetchData
    item = T.Daily(i)
  File "/usr/lib/python2.7/site-packages/habitican_curse/task.py", line 208, in __init__
    self.isDue     = H.isDueDaily(self.data)
  File "/usr/lib/python2.7/site-packages/habitican_curse/helper.py", line 280, in isDueDaily
    if diffDay % (task['everyX']) == 0:
ZeroDivisionError: integer division or modulo by zero
```

**Comment by rbavishi** [comment]
@LordVladneutral I've committed the fix. Although I don't really understand what it means to repeat a daily every "0" days. 

Also, could you clone the repo and test it out before I package it up into a new pypi version? I want to flush out all the bugs before I publish it on the server. Just do a `git clone <repo>` and `./habitican-curse` to start the program. Thanks a lot!

**Comment by LordVladneutral** [comment]
Every 0 day is to disactivate it, it's like having it set for no day of the week.

There still is a bug, I guess. It looks different again, looks good.

```
python2.7 Habitican-curse                                                                                                                                                                           :(
Traceback (most recent call last):
  File "habitican-curse", line 54, in <module>
    curses.wrapper(main)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "habitican-curse", line 41, in main
    G.intf.Init()
  File "/home/william/Habitican-Curse/habitican_curse/interface.py", line 46, in Init
    G.HabitMenu.Init()
  File "/home/william/Habitican-Curse/habitican_curse/menu.py", line 275, in Init
    self.items[i].SetXY(X, Y)
  File "/home/william/Habitican-Curse/habitican_curse/menu.py", line 74, in SetXY
    self.SetStatusXY()
  File "/home/william/Habitican-Curse/habitican_curse/menu.py", line 78, in SetStatusXY
    self.status.SetXY(self.x, self.y + self.status.ReturnLenString() - 2)
AttributeError: 'MenuItem' object has no attribute 'status'
```

**Comment by rbavishi** [comment]
@LordVladneutral This seems to happen when you have a habit which is neither positive nor negative. In this case you cannot even score points with it. Do you happen to have such a habit? Again the use-case eludes me :) Just simple reminders without any kind of scoring?

**Comment by LordVladneutral** [comment]
Reminders or additional info in a challenge, yes I happen to have a few of those.

**Comment by rbavishi** [comment]
@LordVladneutral I've added a commit which provides a fix for this issue. Could you pull and check again?

**Comment by LordVladneutral** [comment]
It works and it works wonderfully so far :) That was quite a lot of changes but hopefully this makes the program even better.

At least, I am glad I can use it, Habitica has always needed a lighter interface and Habitican-Curses does just that :)

**Comment by rbavishi** [comment]
Awesome! Thanks a lot for your help and test-cases. You helped us uncover a lot of bugs. It's better if they're found early. I've packaged this up and you can now do a `pip install`

Thanks again!

**Comment by LordVladneutral** [comment]
You are welcome, this was mutually beneficial :-)


BTW ; it works fine as installed with pip install, I think we can close this thread. I'll keep an eye on the project and use it ;)

**Comment by binamkayastha** [comment]
You guys are awesome! I also realized I was installing it with pip (version 3). Once I used pip2.7, it worked like a charm! (I was on archlinux, and that's how the arch repos make distinctions between the different versions of pip).

**Comment by LordVladneutral** [comment]
@binamkayastha I'm on Arch too, hopes this program is still improved cause it's great. If you wanna ask me something about it's use, ask me, I got pretty expert.
