### ISSUE TITLE
Upgrade Habitica API from version 2 -> 3

### ISSUE THREAD

**Issue by crookedneighbor** [rbavishi/Habitican-Curse#9]
Version 2 of the Habitica API will be officially [deactivated on July 15th](http://devs.habitica.com/api-v2-deprecation-notice/). 

[Here is a migration guide](http://devs.habitica.com/api-v2-v3-migration-guide/) for upgrading to version 3. If you have any questions, feel free to reach out on [Github](https://github.com/HabitRPG/habitrpg/issues) or the [Aspiring Comrades Guild](https://habitica.com/#/options/groups/guilds/2ff9822b-27f2-4774-98da-db349b57a38e).

**Comment by jasonuher** [comment]
I've made a first cut at the transition that implements most of the "day to day" functions (marking habits and todos, etc)
 #12

**Comment by jasonuher** [comment]
All of the functionality from the original code is now functional with V3 with the exception of listing of party names.  The new API gives UUIDs, not usernames, so it would require some extra API calls I think.
